## Slicing Examples

### Ex-1

Slicing the numbers 0,7,14,21,28,35 from np array.

In [1]:
import numpy as np

In [2]:
x = np.arange(0, 36, 1).reshape(6,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [3]:
#slicing code
x.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

### Ex-2

Slicing 14,15,20,21

In [4]:
x = np.arange(0, 36, 1).reshape(6,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [5]:
#slicing code
x[2:4,2:4]

array([[14, 15],
       [20, 21]])