## NumPy (Numerical Python)

In [1]:
import numpy as np

### Arrays

In [2]:
arr = [3, 4, 5]
npArr = np.array(arr)
print(npArr)
#pass directly
npArr = np.array([6, 7, 8])
print(npArr)

[3 4 5]
[6 7 8]


In [3]:
#multidimensional array
npArr = np.array([[6, 7, 8, 9], [9, 10, 11, 12]])
print(npArr)

[[ 6  7  8  9]
 [ 9 10 11 12]]


In [4]:
#shape
npArr.shape

(2, 4)

In [5]:
#ndim -- Number of array dimensions.
npArr.ndim

2

In [6]:
#arange returns evenly spaced values within a given interval
npArr = np.arange(0, 22, 3) # start at 0 count up by 3, stop before 22
npArr

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [7]:
#reshape returns an array with the same data with a new shape.
npArr = npArr.reshape(2,4) # reshape array to be 2x4
npArr

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21]])

In [8]:
#resize changes the shape and size of array in-place.
np.resize(npArr, (3, 2))


array([[ 0,  3],
       [ 6,  9],
       [12, 15]])

In [9]:
#linspace returns evenly spaced numbers over a specified interval.
np.linspace(0, 8, 6) # return 6 evenly spaced values from 0 to 8

array([ 0. ,  1.6,  3.2,  4.8,  6.4,  8. ])

In [10]:
#Create an array using repeating list
np.array([1, 2, 3] * 3)
#same as 
np.tile([1, 2, 3], 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [11]:
#Repeat elements of an array using repeat.
np.repeat([9, 8, 7], 3)

array([9, 9, 9, 8, 8, 8, 7, 7, 7])

### Special Arrays

In [12]:
#eye
np.ones((3, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [13]:
#zeros
np.zeros((2, 2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [14]:
#diag -- Extract a diagonal or construct a diagonal array.
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### Operations

#### dot

For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation). For N dimensions it is a sum product over the last axis of a and the second-to-last of b.

In [15]:
a=np.array([[1,2],[3,4]])
b=np.array([[11,12],[13,14]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]


In [16]:
np.dot(a, b)
#calculation:
#1*11+2*13 1*12+2*14
#3*11+4*13 3*12+4*14

array([[37, 40],
       [85, 92]])

#### inner

Ordinary inner product of vectors for 1-D arrays (without complex conjugation), in higher dimensions a sum product over the last axes.

In [17]:
np.inner(a,b)
#calculation: 
#1*11+2*12, 1*13+2*14 
#3*11+4*12, 3*13+4*14 

array([[35, 41],
       [81, 95]])

#### transpose

Permute the dimensions of an array.

In [18]:
a = np.array([[1, 2], [3, 4]])
print(a)
print('transposing..')
print(a.transpose())
#same as T
print(a.T)

[[1 2]
 [3 4]]
transposing..
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


### Math Functions On Arrays

In [19]:
a = np.array([-4, -2, 1, 3, 5])

In [20]:
a.sum()

3

In [21]:
a.min()

-4

In [22]:
a.max()

5

In [23]:
#Compute the standard deviation along the specified axis.
#Returns the standard deviation, a measure of the spread of a distribution, of the array elements
a.std()

3.2619012860600183

In [24]:
#Compute the arithmetic mean along the specified axis.
#Returns the average of the array elements. 
a.mean()

0.59999999999999998

In [25]:
#Returns the indices of the maximum values along an axis.
a.argmax()

4

In [26]:
#Returns the indices of the minimum values along an axis.
a.argmin()

0